import type { Product } from "./ProductCard";

const names = [
  ["ChatGPT Plus", "AI Tools", "GPT-4o & GPT-5 access with priority"],
  ["Midjourney Pro", "AI Tools", "Premium AI image generation suite"],
  ["Claude Opus", "AI Tools", "Anthropic's most powerful model"],
  ["Gemini Advanced", "AI Tools", "Google's premium AI assistant"],
  ["Perplexity Pro", "AI Tools", "AI-powered research engine"],
  ["Runway Gen-3", "Video Editing", "Cinematic AI video generation"],
  ["ElevenLabs", "AI Tools", "Realistic AI voice cloning studio"],
  ["Notion AI", "Productivity", "Smart workspace with AI built-in"],
  ["Netflix Premium", "Streaming Apps", "4K Ultra HD on multiple devices"],
  ["Spotify Family", "Streaming Apps", "Ad-free music for the whole family"],
  ["Disney+ Bundle", "Streaming Apps", "Disney, Hulu and ESPN+ together"],
  ["YouTube Premium", "Streaming Apps", "Ad-free YouTube and Music"],
  ["HBO Max", "Streaming Apps", "Premium movies and originals"],
  ["Apple TV+", "Streaming Apps", "Award-winning Apple originals"],
  ["Adobe Creative Cloud", "Design Software", "All Adobe apps in one bundle"],
  ["Figma Pro", "Design Software", "Collaborative interface design"],
  ["Canva Pro", "Design Software", "Drag and drop premium design"],
  ["Sketch", "Design Software", "Vector design for Mac"],
  ["Framer Pro", "Design Software", "Design and ship sites instantly"],
  ["Webflow CMS", "Design Software", "Visual website builder pro plan"],
  ["Coursera Plus", "Learning Platforms", "Unlimited access to 7,000+ courses"],
  ["Udemy Business", "Learning Platforms", "26,000+ on-demand courses"],
  ["Skillshare Premium", "Learning Platforms", "Creative classes from experts"],
  ["MasterClass", "Learning Platforms", "Learn from world-class instructors"],
  ["LinkedIn Learning", "Learning Platforms", "Professional skill development"],
  ["Datacamp Pro", "Learning Platforms", "Master data science & AI"],
  ["Microsoft 365", "Productivity", "Word, Excel, PowerPoint and more"],
  ["Google Workspace", "Productivity", "Business email, docs, drive"],
  ["Slack Pro", "Productivity", "Team collaboration upgraded"],
  ["Zoom Pro", "Productivity", "HD video meetings without limits"],
  ["Asana Premium", "Productivity", "Project management for teams"],
  ["ClickUp Unlimited", "Productivity", "All-in-one productivity suite"],
  ["GitHub Copilot", "Developer Tools", "AI pair programmer for VS Code"],
  ["JetBrains All-Pack", "Developer Tools", "Every JetBrains IDE in one license"],
  ["Cursor Pro", "Developer Tools", "AI-first code editor"],
  ["Linear Plus", "Developer Tools", "Modern issue tracking for teams"],
  ["Vercel Pro", "Developer Tools", "Frontend cloud platform"],
  ["Supabase Pro", "Developer Tools", "Postgres backend with auth & storage"],
  ["Semrush Guru", "Marketing", "SEO and competitor research"],
  ["Ahrefs Standard", "Marketing", "Backlinks and keyword research"],
  ["HubSpot Pro", "Marketing", "CRM and marketing automation"],
  ["Mailchimp Standard", "Marketing", "Email marketing and automation"],
  ["Buffer Team", "Marketing", "Schedule social media at scale"],
  ["Hootsuite Pro", "Marketing", "Social media management suite"],
  ["Final Cut Pro", "Video Editing", "Pro video editing for Mac"],
  ["DaVinci Resolve Studio", "Video Editing", "Hollywood-grade color and editing"],
  ["Adobe Premiere", "Video Editing", "Industry-standard video editor"],
  ["CapCut Pro", "Video Editing", "Mobile-first AI video editor"],
  ["Descript Pro", "Video Editing", "Edit video like a doc, with AI"],
  ["VEED.IO", "Video Editing", "Online AI video creation suite"],
  ["1Password Family", "Productivity", "Secure password manager"],
  ["NordVPN", "Productivity", "Private and secure browsing"],
  ["Surfshark", "Productivity", "Unlimited devices VPN"],
  ["Grammarly Premium", "AI Tools", "AI writing assistant pro"],
  ["Quillbot Premium", "AI Tools", "Paraphrase and rewrite with AI"],
  ["Jasper AI", "AI Tools", "Marketing copy AI assistant"],
  ["Copy.ai Pro", "Marketing", "AI copywriting for teams"],
  ["Pictory AI", "Video Editing", "Turn long videos into shorts"],
  ["Synthesia Pro", "Video Editing", "AI avatar video generator"],
  ["Topaz Photo AI", "Design Software", "Sharpen and enhance photos with AI"],
];

const gradients = [
  "from-purple-600 via-fuchsia-500 to-cyan-500",
  "from-cyan-500 via-blue-600 to-indigo-700",
  "from-pink-500 via-rose-500 to-orange-500",
  "from-emerald-500 via-teal-500 to-cyan-600",
  "from-violet-600 via-purple-600 to-pink-600",
  "from-indigo-600 via-blue-500 to-cyan-400",
  "from-orange-500 via-red-500 to-pink-600",
  "from-fuchsia-600 via-purple-700 to-indigo-700",
  "from-teal-500 via-cyan-500 to-blue-600",
  "from-amber-500 via-orange-500 to-red-600",
];

const badges: Product["badge"][] = ["Trending", "Best Seller", "Popular", "Limited Offer", undefined, undefined];

export const products: Product[] = names.map((n, i) => {
  const original = 19 + ((i * 7) % 130);
  const price = Math.max(4, Math.round(original * (0.2 + ((i * 11) % 30) / 100)));
  const initials = n[0].split(" ").map((w) => w[0]).slice(0, 2).join("").toUpperCase();
  return {
    id: i + 1,
    name: n[0],
    category: n[1],
    desc: n[2],
    original,
    price,
    rating: Number((4.4 + ((i * 13) % 6) / 10).toFixed(1)),
    badge: badges[i % badges.length],
    initials,
    gradient: gradients[i % gradients.length],
  };
});
