// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { getPublicEnv, getServerEnv } from "@/config/env";

function createSupabaseClient() {
  const { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } =
    typeof window === "undefined"
      ? (() => {
          const e = getServerEnv();
          return { SUPABASE_URL: e.SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY: e.SUPABASE_PUBLISHABLE_KEY };
        })()
      : (() => {
          const e = getPublicEnv();
          return { SUPABASE_URL: e.VITE_SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY: e.VITE_SUPABASE_PUBLISHABLE_KEY };
        })();

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
